### ISSUE TITLE
Make results greppable/conditional exit code

### ISSUE THREAD

**Issue by aequitas** [rbsec/sslscan#109]
For automated testing it would be nice to have a better way to extract information about weak/bad cryptos.

For example to have the classification given to colored output (yellow for weak cryptos) to be include the colors word when --no-color is selected, eg:

```
sslscan --no-color example.com | grep yellow
...
Accepted  TLSv1.0 (yellow)  256 bits  DHE-RSA-CAMELLIA256-SHA       DHE 1024 (yellow) bits
...
```

or

```
sslscan --no-color example.com | grep weak
...
Accepted  TLSv1.0 (weak)  256 bits  DHE-RSA-CAMELLIA256-SHA       DHE 1024 (weak) bits
...
```

Or maybe a feature to set the exit code to non-zero when a specific condition is met, this can be enabled with a command line option.

```
sslscan --set-exit-code-weak-crypto --set-exit-code-weak-protocol example.com

sslscan --set-exit-code-all example.com
```

**Comment by rbsec** [comment]
If you want to programatically parse the output you're much better off using the XML output (--xml) rather than tryingto grep the console output. You can also pipe the XML to STDOUT with `--xml=-`.
