### ISSUE TITLE
Unable to Compile .c in Cygwin

### ISSUE THREAD

**Issue by flamecopper** [rbsec/sslscan#123]
Hi All,

For some reason I was unable to compile the .c library in Cygwin using GCC. I would appreciate if someone could give me the direct link to the .exe download as I need the coloured version

$ gcc sslscan.c -o sslscan.exe
sslscan.c: In function ‘tcpConnect’:
sslscan.c:460:13: warning: implicit declaration of function ‘strnstr’ [-Wimplicit-function-declaration]
         if (strnstr(buffer, ok, BUFFERSIZE)) {
             ^
sslscan.c: In function ‘main’:
sslscan.c:3742:177: error: ‘VERSION’ undeclared (first use in this function)
         fprintf(options.xmlOutput, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<document title=\"SSLScan Results\" version=\"%s\" web=\"http://github.com/rbsec/sslscan\">\n", VERSION);
                                                                                                                                                                                 ^
sslscan.c:3742:177: note: each undeclared identifier is reported only once for each function it appears in

**Comment by rbsec** [comment]
You are trying to compile just sslscan.c without including any of the headers. Please see the Makefile for how to build sslscan.
