### ISSUE TITLE
Cant cross-compile sslscan 1.11.10 for windows x64 on debian testing

### ISSUE THREAD

**Issue by mleone87** [rbsec/sslscan#141]
Hi

following INSTALL

I. Cross-compiling from Linux

  A. Building a 64-bit Windows executable

    0.) Install Mingw-w64.  On Debian-like systems, this can be done with:
        apt-get install mingw-w64

    1.) Download and compile OpenSSL with the following:
	git clone https://github.com/openssl/openssl
	git checkout OpenSSL_1_0_2-stable
        ./Configure --cross-compile-prefix=x86_64-w64-mingw32- \
            -fstack-protector-all -D_FORTIFY_SOURCE=2 mingw64 shared
        make

    2.) Compile sslscan with the path to the OpenSSL directory:
        make -f Makefile.mingw OPENSSL_PATH=../path/to/openssl

The procedure is ok until I compile sslscan, with that error:

**sslscan.c:93:23: fatal error: arpa/inet.h: File o directory non esistente
 #include <arpa/inet.h>
                       ^
compilation terminated.**

My system is a fresh install of debian testing with all dependencies required in the README

**Comment by rbsec** [comment]
Do you have the `libc6-dev` package installed? It should be installed with `build-essential`, which is listed in the README.

**Comment by mleone87** [comment]
yes, all dependencies are installed

**Comment by birou007** [comment]
I tried removing the `#include <arpa/inet.h>` and it cross-compiles just fine on Ubuntu and the resulting binary worked for me on Windows.

**Comment by gkapell** [comment]
Hello,

I had the same issue and I solve it like this.

In sslscan.c I modify the line #include <arpa/inet.h> to

#ifdef __linux__
    #include <arpa/inet.h>
#endif

After that the compile using mingw64 completed successfully.


Thank you,
George

**Comment by rbsec** [comment]
@gkapell I've implemented your fix, seems to compile on Linux fine.
