### ISSUE TITLE
Insecure Renegotiation not checked if Secure Renegotiation is active?

### ISSUE THREAD

**Issue by MartinSchroers** [rbsec/sslscan#142]
Could it be that the insecure renegotiation check is omitted by the 'else if' statement if secure renegotiation is found?

// Test renegotiation
int outputRenegotiation(   struct sslCheckOptions *options, struct renegotiationOutput *outputData)
   {
    
   printf_xml("  <renegotiation supported=\"%d\"   secure=\"%d\" />\n",
   outputData->supported, outputData->secure);
    
   if   (outputData->secure)
   {
   printf("%sSecure%s session renegotiation supported\n\n", COL_GREEN,   RESET);
   }
   else if   (outputData->supported)
   {
   printf("%sInsecure%s session renegotiation supported\n\n", COL_RED,   RESET);
   }
   else
   {
   printf("Session renegotiation %snot supported%s\n\n", COL_GREEN,   RESET);
   }
    
   return   true;
   }

**Comment by rbsec** [comment]
This function is just to output the findings of the `testRenegotiation` function which does the actual check - that has already run at this point.
