### ISSUE TITLE
Unable to compile 32-bit SSLScan 

### ISSUE THREAD

**Issue by MikeLim7** [rbsec/sslscan#148]
Many thanks for new 1.11.11 release! It fixes 64-bit windows binary compile on Kali.

However, I am unable to compile the 32-bit Windows binary on Ubuntu 14.04 server (32-bit) with mingw.

Error below
>/usr/bin/i586-mingw32msvc-gcc -Iopenssl_mingw/include -D__USE_GNU -DVERSION=\""1.11.11 Windows 32-bit (Mingw)"\"  -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Wl,-O1 -Wl,--discard-all -Wl,--no-undefined -Wl,--dynamicbase -Wl,--nxcompat -static -o sslscan.exe sslscan.c openssl_mingw/libssl.a openssl_mingw/libcrypto.a zlib_mingw/libz.a -lws2_32 -lgdi32
>/tmp/ccbXXrvd.o:sslscan.c:(.text+0x8302): undefined reference to `_inet_ntop'
>/tmp/ccbXXrvd.o:sslscan.c:(.text+0x8387): undefined reference to `_inet_ntop'
>collect2: ld returned 1 exit status
>make: *** [sslscan] Error 1
>

I am able to compile if the inet_ntop function  (line 3089 and 3096) is commented out.
Guess the inet_ntop implementation is missing.

>user@ubuntu:/$ /usr/bin/i586-mingw32msvc-gcc --version
>i586-mingw32msvc-gcc (GCC) 4.2.1-sjlj (mingw32-2)
>Copyright (C) 2007 Free Software Foundation, Inc.

**Comment by jtesta** [comment]
@MikeLim7: I wrote the original Windows cross-compile support for sslscan.  While this issue is (probably) fixable, I'm wondering if its worth continuing to support 32-bit builds.  Do you really have a need for them, or were you just experimenting?

**Comment by MikeLim7** [comment]
@jtesta: Good question.  We have 32-bit Windows Server 2008 and windows desktops around, so a 32-bit version does help.  I had a look at the code and the compilation fails due the additional inet_ntop line that was added. 


>if (ai->ai_family == AF_INET6)
 >       {
>            ...
 >           inet_ntop(ai->ai_family, &options->serverAddress6.sin6_addr, options->addrstr, sizeof(options->addrstr));
  >      }
  >      else
  >     {
>       ...
  >          inet_ntop(ai->ai_family, &options->serverAddress.sin_addr, options->addrstr, sizeof(options->addrstr));
 >       }
>

 I do agree with you that we should stop supporting 32-bit in a future version. Assuming that the above line does not affect any functionality, perhaps we can release this 32-bit binary and discontinue 32-bit Windows binary support in a future versions.

**Comment by jtesta** [comment]
@MikeLim7 I just issued a pull request which fixes 32-bit builds by including glibc's implementation of inet_ntop().  Please give it a whirl and let me know if you run into any trouble.

**Comment by MikeLim7** [comment]
@jtesta Thanks for the pull request. 
I must confess I could not figure out how to get the change files down, so I manually merge the changes and download win32bit-compat.h file.

Your Makefile.mingw  seems incorrect. 
>if**n**eq ($(BUILD_32BIT),)
>   DEFINES=-DBUILD_32BIT=1
>endif

Should it be ifeq instead of ifneq?

>ifeq ($(BUILD_32BIT),)
>   DEFINES=-DBUILD_32BIT=1
>endif

I was able to compile on Ubuntu 14.04 32-bit after making this change. Did some limited testing and it works fine on XP, Vista and 2008 server 32-bit. Thanks

**Comment by jtesta** [comment]
> I must confess I could not figure out how to get the changed files down, so I manually merge the changes and download win32bit-compat.h file.

You can do:
`git clone -b win32_fix https://github.com/jtesta/sslscan`

> Should it be ifeq instead of ifneq? [...] I was able to compile on Ubuntu 14.04 32-bit after making this change.

Nope, its correct as-is.  Did you run it with the BUILD_32BIT=1 flag?  It should be built like this:
`make -f Makefile.mingw BUILD_32BIT=1`

I just checked it again, and it does indeed work.  Maybe you didn't manually merge in all the changes correctly?  Try copy/pasting the clone and make commands above and see if it works for you.

**Comment by MikeLim7** [comment]
Got it. I am able to compile now. Thanks!
