### ISSUE TITLE
STARTTLS fails on some hosts

### ISSUE THREAD

**Issue by corny** [rbsec/sslscan#15]
The following line results in `The SMTP service on 217.69.254.95 port 25 did not appear to support STARTTLS`:
```
sslscan --starttls-smtp 217.69.254.95
```

It works well with `openssl s_client`:
```
openssl s_client -starttls smtp -connect 217.69.254.95:25
```

**Comment by rbsec** [comment]
Not run into this issue since making the changes above, so closing for now.

**Comment by fluggelgleckheimlen** [comment]
I was able to repoduce the issue using **mx1.cesactivationprod.iphmx.com** or **mx2.cesactivationprod.iphmx.com**, these hosts has a strict rate limit (10 connections per second or less) and you will get:
```
ERROR: The host mx1.cesactivationprod.iphmx.com on port 25 did not appear to be an SMTP service.
ERROR: Could not connect.
```
Instead of the original smtp error:
```
421 #4.4.5 Too many connections from your host.
```
