### ISSUE TITLE
sslscan stops on "Resource temporarily unavailable"

### ISSUE THREAD

**Issue by corny** [rbsec/sslscan#16]
Some hosts seem to be overwhelmed by the requests of sslscan.

If i run `./sslscan --starttls-smtp --failed 68.232.139.67` then it stops after a couple of tested ciphers and shows the message "Resource temporarily unavailable". Sometimes it happens ealier, sometimes later.

In such a case it could help to wait few seconds and retry the failed cipher. Any other ideas?

**Comment by matlink** [comment]
I got the same error even when I launch the command with the sleep option (5000 ms)

**Comment by rbsec** [comment]
If you connet to the server with telnet/ncat/whatever and do the EHLO/STARTTLS manually, what response do you get back?

Some servers react badly to the heartbleed/renegotiation tests, so you could try disabling those (--no-heartbleed --no-renegotiation --no-compression) and see if that makes any difference.

Ultimately I don't think there's much that can be done here. Some mailservers are very agressive at blocking people (for spam reasons), so other than pushing the sleep time even higher, I don't really see many options..

**Comment by matlink** [comment]
It's strange, I have now a working version from a friend and everything
is working well.
