### ISSUE TITLE
build_openssl_debian.sh failure with bash

### ISSUE THREAD

**Issue by mattlyons0** [rbsec/sslscan#160]
https://github.com/rbsec/sslscan/blob/dbfeee90c446e5948e7dc33fc51592b76e934a8b/build_openssl_debian.sh#L29
Crashes with `-bash: cd: too many arguments`

Replacing that line with `cd $(find . -maxdepth 1 -type d -iname 'openssl*')` works fine.

**Comment by janiko71** [comment]
Or `cd openssl-*` in my case works well too.
