### ISSUE TITLE
Chacha cipher

### ISSUE THREAD

**Issue by ealashwali** [rbsec/sslscan#162]
I am sure (by manual testing from a browser that only supports: `ecdhe_rsa_chacha20_poly1305_sha256`) that "google.com" supports `ecdhe_rsa_chacha20_poly1305_sha256`. However, when I perform a scan using: `sslscan google.com` I do not get this cipher accepted. Can you please clarify. Am I missing something or this is a bug?

**Comment by ealashwali** [comment]
Could you please specify what is the default cipher list that sslascan client uses in the testing? Can I specif the ciphers list? I am using: 4.14.9-kali3-amd64

**Comment by rbsec** [comment]
The ciphers that sslscan supports will depend on the underlying version of OpenSSL that it was built against. You can print out a list of supported ciphers with `--show-ciphers`.

Assuming it was build statically, it's using Peter Mosmans' build of OpenSSL, which backported the CHACHA20 ciphers:

https://github.com/PeterMosmans/openssl

Can you try connecting to the site manually using the OpenSSL client (from the version sslscan was built against)? `./openssl s_client -connect google.com:443 -cipher ECDHE-RSA-CHACHA20-POLY1305`?

If that fails but the site actually supports the ciphersuite, then it must be a bug in the upstream OpenSSL version.

**Comment by ealashwali** [comment]
`--show-ciphers` in sslscan shows me the CHACHA cipher. But the scan result for a website that does support it is incorrect (i.e. sslscan shows that the site does not support it).

**Comment by ealashwali** [comment]
FYI, I tested "facebook.com" using sslscan and the scan result shows "chacha" cipher. However, I do not have explanation on why the tool does not show "chacha" with "google.com" although I can connect to it using "chacha" in a browser. Regarding your question about testing it with OpenSSL, which openssl (the forked one? you mean I compile it separately and try it?).

**Comment by ealashwali** [comment]
I am not sure if I installed the forked OpenSSL from [here](https://github.com/PeterMosmans/openssl/blob/1.0.2-chacha/INSTALL)  correctly. But here is the result (the I was running command below from inside the `openssl-1.0.2-chacha` directory that I downloaded from [here](https://github.com/PeterMosmans/openssl) : 
```
Downloads/openssl-1.0.2-chacha$ openssl s_client -cipher 'ECDHE-RSA-CHACHA20-POLY1305' -connect google.com:443
Error with command: "-cipher ECDHE-RSA-CHACHA20-POLY1305"
140178295436952:error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:ssl_lib.c:1380:
```
How can I make sure I am running PeterMosmans version (I installed it manually following [these instructions](https://github.com/PeterMosmans/openssl/blob/1.0.2-chacha/INSTALL). I tried: `openssl version -a` and this is the result: 
```
OpenSSL 1.0.2g  1 Mar 2016
built on: reproducible build, date unspecified
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: cc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wa,--noexecstack -Wall -DMD32_REG_T=int -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/lib/ssl"
```

**Comment by sergeevabc** [comment]
> $ openssl s_client -connect google.com:443 -cipher ECDHE-RSA-CHACHA20-POLY1305
OK, I’m connected.

> $ sslscan google.com
No mention of CHACHA20… Why?

**Comment by rbsec** [comment]
Closing off some old issues.
