### ISSUE TITLE
sslscan.c:94:25: fatal error: openssl/err.h: No such file or directory compilation terminated.

### ISSUE THREAD

**Issue by ealashwali** [rbsec/sslscan#163]
I am trying to install sslscan in ubuntu. First, I installed openssl-chacha from [here](https://github.com/PeterMosmans/openssl/blob/1.0.2-chacha/INSTALL)
Then, I followed the instructions [here](https://github.com/rbsec/sslscan). The first thing I did is: `make` Note that it is unclear to me when to use these commands (I did not execute them). But I want to use the chacha version of openssl:
```
apt-get install build-essential git zlib1g-dev
apt-get build-dep openssl
make static
```
When I try to run the command: `make ` I get this error:
```
make: git: Command not found
cc -o sslscan -Wall -Wformat=2 -Wformat-security -pie -z relro -z now -L/usr/local/lib -L/usr/local/ssl/lib -L/usr/local/opt/openssl/lib -L/opt/local/lib -D_FORTIFY_SOURCE=2 -fstack-protector-all -fPIE -I/usr/local/include -I/usr/local/ssl/include -I/usr/local/ssl/include/openssl -I/usr/local/opt/openssl/include -I/opt/local/include -I/opt/local/include/openssl  -DVERSION=\"1.11.11\" sslscan.c -lssl -lcrypto -ldl
/usr/bin/ld: /usr/local/ssl/lib/libssl.a(s2_clnt.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/ssl/lib/libssl.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:91: recipe for target 'sslscan' failed
make: *** [sslscan] Error 1
```
I am in this directory: `/home/myuser/Downloads/sslscan-master`
I made sure that openssl in:
`/usr/local/ssl`
Can you please point to me what is missing? I am not familiar with Linux system (Windows user) but I prefer to use the tool in Linux. So I will appreciate your help and patience.

**Comment by rbsec** [comment]
Did the `apt-get` commands complete successfully? The first line of the output looks like `git` isn't installed properly.

You shouldn't need to install your own version of OpenSSL, `make static` will pull down and compile the correct version. It does this using `git`, so if `git` isn't working that would explain why the build fails.

**Comment by ealashwali** [comment]
I tried to run: `make static`. This is what I got:
```
c_zlib.c:25:19: fatal error: zlib.h: No such file or directory
compilation terminated.
Makefile:70: recipe for target 'depend' failed
make[3]: *** [depend] Error 1
make[3]: Leaving directory '/home/e/Downloads/sslscan-master/openssl/crypto/comp'
Makefile:133: recipe for target 'depend' failed
make[2]: *** [depend] Error 1
make[2]: Leaving directory '/home/e/Downloads/sslscan-master/openssl/crypto'
Makefile:475: recipe for target 'depend' failed
make[1]: *** [depend] Error 1
make[1]: Leaving directory '/home/e/Downloads/sslscan-master/openssl'
Makefile:133: recipe for target 'openssl/libcrypto.a' failed
make: *** [openssl/libcrypto.a] Error 2
```

**Comment by ealashwali** [comment]
After executing: 
`apt-get install build-essential git zlib1g-dev`
`make static`
NOTE: I got error on `apt-get build-dep openss` saying: 
```
Reading package lists... Done
E: You must put some 'source' URIs in your sources.list
```
I got this final lines:
```
make sslscan STATIC_BUILD=TRUE
make[1]: Entering directory '/home/e/Downloads/sslscan-master'
fatal: Not a git repository (or any of the parent directories): .git
cc -o sslscan -Wall -Wformat=2 -Wformat-security -pie -z relro -z now -L/home/e/Downloads/sslscan-master/openssl/ -D_FORTIFY_SOURCE=2 -fstack-protector-all -fPIE -I/home/e/Downloads/sslscan-master/openssl/include/ -I/home/e/Downloads/sslscan-master/openssl/  -DVERSION=\"1.11.11-static\" sslscan.c -lssl -lcrypto -lz -ldl

```
Can you please advise?

**Comment by ealashwali** [comment]
I installed `git` successfully and the `make static` seems completed successfully. However, when I move to execute either `make` or `gcc -lssl -o sslscan sslscan.c` I get:
```
sslscan.c:94:25: fatal error: openssl/err.h: No such file or directory
compilation terminated.

```
Any help?
