### ISSUE TITLE
Is my version correct?

### ISSUE THREAD

**Issue by ealashwali** [rbsec/sslscan#165]
Hi, I have followed the installation details [here](https://github.com/rbsec/sslscan): 
To test the version, I run: ` ./sslscan --version`. The output I got:
```
1.11.11-rbsec-15-g8fee8a3-static
OpenSSL 1.0.2-chacha (1.0.2g-dev)

```
Can you please confirm to me if this means sslscan installed correctly and uses the chacha-supporting version of OpenSSL? 
My question is due to discrepancy between the output I got and the one your README prints which is:
```
 1.x.y-...-static
 OpenSSL 1.1.0-dev xx XXX xxxx
```
Especially that I got `OpenSSL 1.0.2-chcha` and your says: `OpenSSL 1.1.0-dev`. Sorry for the spam. I will appreciate your help.

**Comment by rbsec** [comment]
You're version is correct  - the readme was outdated and has now been fixed.
