### ISSUE TITLE
Possible condition bug

### ISSUE THREAD

**Issue by mfr-itr** [rbsec/sslscan#166]
https://github.com/rbsec/sslscan/blob/8fee8a3453d9f6b1ae04d7877b2386178f9590d4/sslscan.c#L1027-L1031

The two conditions seem to be the same.

I also got a "Server doesn't support TLS - skipping TLS Fallback SCSV check" message on a serveur with TLS1.[0-2] activated. Maybe it's related to this issue? Or is it "doesn't support SSL"?

**Comment by rbsec** [comment]
Good spot, the first one should have been `TLS1_1_VERSION` (TLS 1.1) not `TLS1_VERSION` (TLS 1.0)

**Comment by rbsec** [comment]
That message should only happen when the server doesn't support any TLS versions (just SSL), but it's possibly related to this bug. Do you still get it with the updated version?

**Comment by mfr-itr** [comment]
It's in a client's private network, so I can't test it ;)
I'll report if I get this error again. Thanks!
