### ISSUE TITLE
TLS 1.2 send() failed: Bad file descriptor

### ISSUE THREAD

**Issue by sjhorvath1** [rbsec/sslscan#169]
Running on a Windows 7 VM, errors out at Heartbleed:
"TLS 1.2 send() failed: Bad file descriptor"

**Comment by sjhorvath1** [comment]
Closed, Problem Exists Between Keyboard and Chair

**Comment by vijayaraja** [comment]
i am facing same issue. what do you mean by "Problem Exists Between Keyboard and Chair"

**Comment by hackinwolf** [comment]
For those here wondering why this error resulted, the error for me resulted from the Symantec Endpoint Protection blocking sslscan's attempt to check for the Heartbleed vulnerability, as SEP views it as being potentially malicious.
