### ISSUE TITLE
import the result in DefectDojo

### ISSUE THREAD

**Issue by NRGLine4Sec** [rbsec/sslscan#180]
What is the better argument or the combinaison of argument to create a report file which can be imported in [DefectDojo](https://github.com/DefectDojo/django-DefectDojo).
I have create an issue in DefectDojo to add the ability to import the result of a scan with sslscan (https://github.com/DefectDojo/django-DefectDojo/issues/1187) but, maybe you can help us to add sslscan to DefectDojo.

**Comment by rbsec** [comment]
The easiest way would be to parse the XML output from `--xml`, which contains all the information in stdout. Based on the XSLT related changes in #54 it also includes an estimation of cipher strength (based on the same decisions as the colouring in the output). Whether or not the things it flags count as vulnerabilities will depend a lot on the context of the system you're testing.
