### ISSUE TITLE
[Feature request] openssl-iana mapping

### ISSUE THREAD

**Issue by noraj** [rbsec/sslscan#182]
Add support for openssl-iana cipher name mapping like in testssl https://github.com/drwetter/testssl.sh/blob/3.0/openssl-iana.mapping.html

And so add options:

- `--openssl-naming` (default, implicit): display openssl names
-  `--iana-naming`: display iana names instead
- providing both options show both names

**Comment by maikimaiko** [comment]
That'd be awesome

**Comment by rbsec** [comment]
Displaying both options will probably mess up the output (especially given how long some of the IANA names are), but they can certainly both be in the XML, and an option to choose which one you want on STDOUT seems reasonable.

OpenVPN look like they have a mapping already, which might save a bit of work:

https://github.com/OpenVPN/openvpn/blob/master/src/openvpn/ssl.c#L269

**Comment by noraj** [comment]
The testssl mapping is already in XML format.

**Comment by rbsec** [comment]
Implemented in #256
