### ISSUE TITLE
Display key exchange information

### ISSUE THREAD

**Issue by HQJaTu** [rbsec/sslscan#184]
During SSL/TLS-connection a key exchange is performed. This key exchange is signed and using a hash algorithm (something completely different from cipher suite), but the one used is not displayed. This is vital information and must be known.

It is quite easy to create a scenario where cipher suite used is valid, but the actual key is exchanged using a weak algorithm. Chrome beginning from version 72 will complain about this, but there are not many other tools which will.

**Comment by rbsec** [comment]
It looks like this could be tested in the same way as ciphers by trying to connect with each algorithm using `SSL_CTX_set1_sigalgs()`.

https://www.openssl.org/docs/man1.1.0/man3/SSL_CTX_set1_sigalgs_list.html

I'll add this to the todo list, but to be honest I don't have a huge amount of time to be spending on sslscan at the moment, so it may not be particularly soon I'm afraid.

**Comment by jtesta** [comment]
@HQJaTu : could you give the new `sslscan2` branch a try?  We added code to enumerate all key exchanges and server signature algorithms.

Please let us know if it gives the expected output.  That would be a big help for testing under real-world conditions!

**Comment by HQJaTu** [comment]
Whoa. Thanks!
It works!

Example:
```
  Server Signature Algorithm(s):
TLSv1.3  rsa_pss_rsae_sha256
TLSv1.3  rsa_pss_rsae_sha384
TLSv1.3  rsa_pss_rsae_sha512
TLSv1.2  rsa_pkcs1_sha1
TLSv1.2  rsa_pkcs1_sha224
TLSv1.2  rsa_pkcs1_sha256
TLSv1.2  rsa_pkcs1_sha384
TLSv1.2  rsa_pkcs1_sha512
TLSv1.2  rsa_pss_rsae_sha256
TLSv1.2  rsa_pss_rsae_sha384
TLSv1.2  rsa_pss_rsae_sha512
```

The really good thing with sslscan is, now I know my server does have `TLSv1.2  rsa_pkcs1_sha1` there. Last year, when I was working with the topic of server signature hash, in my blog post (https://blog.hqcodeshop.fi/archives/462-Deprecated-SHA-1-hashing-in-TLS.html) I wrote "_there is nothing you can do to fix_". Now that I have a tool, which *clearly* measures and indicates the reality, I can approach Nginx-project with an obvious follow-up question: "HOW can you affect the set of supported server signature algorithms?"

Again. Thank you for this. To my knowledge this is the first tool after Chrome to have any kind of checking, indication or measurement of server signature hashes. This is ground-breaking stuff!

**Comment by jtesta** [comment]
Great to hear that it works well for you!  Giving users output to take back to developers is exactly what I was aiming for!

I think the plan is to release sslscan v2.0 relatively soon.  Since lots of code has changed, though, we do need help with testing.  If you could keep an eye out on the alpha/beta releases and ensure they keep producing the expected results, that would be a huge help!  Thanks!

**Comment by rbsec** [comment]
It'll be interesting if these checks start to get picked up by other tools (and if vendors start giving you a bit more control them - which doesn't really exist at the moment). Thanks for your testing and feedback - always very much appreciated.
