### ISSUE TITLE
Compilation on Debian results in errors

### ISSUE THREAD

**Issue by Dietbrand** [rbsec/sslscan#193]
While compiling the following errors occur on a fresh Debian Jessie (8) and Wheezy (7). We still provide support for these Distributions as sslscan is used to test Postfix functionality.

sslscan.c: In function ‘resolveCipherID’:
sslscan.c:4880:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
   for (int i = 0; i < (sizeof(missing_ciphersuites) / sizeof(struct missing_ciphersuite)); i++) {
   ^
sslscan.c: In function ‘tlsExtensionAddDefaultKeyShare’:
sslscan.c:4988:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
   for (int i = 0; i < 32; i++) {
   ^
sslscan.c: In function ‘makeClientHello’:
sslscan.c:5082:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
   for (int i = 1; i < 8; i++) {
   ^
sslscan.c: In function ‘testSupportedGroups’:
sslscan.c:5331:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for (int i = 0; i < (sizeof(group_key_exchanges) / sizeof(struct group_key_exchange)); i++) {
     ^
sslscan.c:5348:9: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
         for (int j = 0; j < key_exchange_len; j++) {
         ^
sslscan.c: In function ‘testSignatureAlgorithms’:
sslscan.c:5630:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for (int i = 0; i < (sizeof(signature_algorithms) / sizeof(struct signature_algorithm)); i++) {
     ^

I can resolve this by using the following CFLAGS:

CFLAGS  += -D_FORTIFY_SOURCE=2 -fstack-protector-all -fPIE **-std=gnu11**

There was no issue with the compile on Debian Stretch or Buster.

**Comment by rbsec** [comment]
Hi @Dietbrand.

I've never come across this issue myself - it looks like C11 was made the standard for GCC years ago, but I guess that older versions of Debian may not have that. I've added that flag in e4f0474.

Thanks

**Comment by Dietbrand** [comment]
Thank you very much. Our pipelines are successful again now too.
