### ISSUE TITLE
export results as XML

### ISSUE THREAD

**Issue by toxydose** [rbsec/sslscan#200]
.I have sslscan 1.11.13-static pre-installed on Kali Linux distributive,
I am using --xml=file.xml command.
After finishing scanning I can not find the exported file.
Where the file can be stored? I couldn't find it using "find" tool

**Comment by rbsec** [comment]
Hi @toxydose.

The XML file should be created in the current working directory (i.e, the folder you are in when you run sslscan). Do you have permissions to create files in this folder?
