### ISSUE TITLE
implicit declaration of function 'inet_ntop' is invalid in C99

### ISSUE THREAD

**Issue by vollkommenheit** [rbsec/sslscan#204]
Hello, I can build successfully from the latest source, albeit with a warning:
> sslscan.c:3235:13: warning: implicit declaration of function 'inet_ntop' is invalid in C99
      [-Wimplicit-function-declaration]
            inet_ntop(ai->ai_family, &options->serverAddress6.sin6_addr, options->addrstr, sizeof(options->addrstr));
            ^
1 warning generated.

I find just relocating `const char *inet_ntop(int af, const void *src, char *dst, socklen_t size); ` gets rid of that warning: 

`--- sslscan.c	2020-04-26 15:54:27.000000000 -0400`
`+++ sslscan-new.c	2020-04-26 15:53:56.000000000 -0400`
`@@ -82,8 +82,6 @@`
`     #endif`
`   #endif`
` `
`-  const char *inet_ntop(int af, const void *src, char *dst, socklen_t size);`
`-`
`   #ifndef ENABLE_VIRTUAL_TERMINAL_PROCESSING`
`     #define ENABLE_VIRTUAL_TERMINAL_PROCESSING 0x0004`
`   #endif`
`@@ -149,6 +147,8 @@`
` unsigned long SSL_CIPHER_get_id(const SSL_CIPHER* cipher) { return cipher->id; }`
` #endif`
` `
`+const char *inet_ntop(int af, const void *src, char *dst, socklen_t size);`
`+`
` const SSL_METHOD *TLSv1_3_client_method(void)`
` {`
 `    return TLS_client_method();`

**Comment by rbsec** [comment]
That function should be available on Linux and is declared inside an `ifdef` earlier in the file for Windows. What platform are you compiling on?

**Comment by michael-o** [comment]
Same here on FreeBSD 12.

**Comment by rbsec** [comment]
I've pushed a fix for this in 11ff0e5. I don' have a FreeBSD system to check on - but if it's still giving a warning then please let me know.
