### ISSUE TITLE
"strength" attribute missing from the XML output?

### ISSUE THREAD

**Issue by steeve85** [rbsec/sslscan#209]
Hi,

XML files generated by sslscan 2.0.0-beta1 seems to omit the `strength` attribute that used to be in files exported by sslscan 1.11.13.
This breaks the SSLscan parser in DefectDojo (https://github.com/DefectDojo/django-DefectDojo/issues/2428)

Are you planning to add it back? 

Thanks

**Comment by rbsec** [comment]
Hi @steeve85,

Good spot - this was a regression when the main cipher scanning code was rewritten. It's been re-implemented in 2.0.0-beta3.

Just to let you know, there's going to be a change made to how certificates are presented in the XML to better support servers with multiple certificates (see discussion in #208), so if you're parsing that out of the XML then that code will need updating at some point in the near future.
