### ISSUE TITLE
add proxy tunneling

### ISSUE THREAD

**Issue by daytona675** [rbsec/sslscan#212]
Hi,
I would like to make a pull request for an added functionnality.
I can’t have proxy options (to have the possibility to tunneling the http flow to a proxy server).
For exemple, with sslyse I have this possibility and in a legacy environment I can check ssl.
Without this possibility I can’t check

Can you tell me how to make my pull request.

**Comment by rbsec** [comment]
Hi,

You can either make a pull request on GitHub from your forked repository, or if you prefer you can send me a diff/patch file (here or directly).

**Comment by mabed-fr** [comment]
Up ?
