### ISSUE TITLE
SNI Name not sent when --targets file used

### ISSUE THREAD

**Issue by adlan7** [rbsec/sslscan#215]
When using a  --targets file, sniname is blank in the XML output for all domains.  The results also indicate that sniname is not being sent when called on a group of domains.  If I call on a single domain, sniname is populated in the output and the results are as expected.  

When calling with a single hostname, the code appears to copy options.host into options.sniname if a separate sniname is not specified.  This does not occur in the loop.
I tried adding 
                                strncpy(options.sniname, options.host, sizeof(options.host) -1);
at line 4194 of sslscan.c (immediately underneath where the options.host is populated in the loop).  
This had the desired results, but not having used C for many years I'm not sure if I have introduced a memory leak.  
It would also be fantastic to also add a feature to allow specification of an (optional) alternate sniname in the targets file.

[sni.patch.txt](https://github.com/rbsec/sslscan/files/5234959/sni.patch.txt)

**Comment by rbsec** [comment]
Hi @adlan7,

Thanks for reporting this - I very rarely use the `--targets` mode, so I hadn't come across this. I had to amend the patch you suggested, because it would always overwrite `options.sniname` with `options.host` (even if you'd manually specified a different SNI name with `--sni-name`). This should be fixed in version 2.0.1.

**Comment by adlan7** [comment]
Hi @rbsec 
Thanks for the fix. I hadn’t considered combining —targets with —sni-name as I thought it would be unusual to want to specify the same sni name for all hosts, but is is definitely more correct to cater for it

**Comment by rbsec** [comment]
It's certainly an edge case - the only thing I could really think is if you had a load of different IP addresses that were in a load balanced configuration. Still, nice to have it working properly in case anyone else comes up with some strange circumstance when they want to doit.
