### ISSUE TITLE
Version string needs to be improved

### ISSUE THREAD

**Issue by Have-a-question-about-this-project** [rbsec/sslscan#217]
If I download the sslscan-2.0.1.tgz, extract and build, the Makefile tries to get the version from git, which either fails as I din't check out from git, or picks up the git info from another repository of which I happen to be in a sub directory.
If it fails to get a version from git then it tries to pull the version from the Chnagelog file. This would be fine if there was actually a Changelog entry for the release, but there isn't so it finds the latest entry which is 2.0.0.

**Comment by rbsec** [comment]
Hi @Have-a-question-about-this-project,

Looks like I forgot to update the Changelog - I've fixed this in f9378f9.

Thanks.
/close
