### ISSUE TITLE
Build on OSX

### ISSUE THREAD

**Issue by MichaelSchroll** [rbsec/sslscan#22]
I was able to get it built on OSX by:

brew install openssl

And the following changes to the Makefile:

diff --git a/Makefile b/Makefile
index df6546c..76d4497 100644
--- a/Makefile
+++ b/Makefile
@@ -18,8 +18,8 @@ WARNINGS  = -Wall -Wformat=2
 DEFINES   = -DVERSION=\"$(GIT_VERSION)\"

 # for dynamic linkung
-LDFLAGS   = -L/usr/local/ssl/lib/
-CFLAGS    = -I/usr/local/ssl/include/ -I/usr/local/ssl/include/openssl/
+LDFLAGS   = -L/usr/local/opt/openssl/lib
+CFLAGS    = -I/usr/local/opt/openssl/include
 LIBS      = -lssl -lcrypto

 # for static linking

I'm not versed in how best to share this, or I'd do a pull request. Appreciate help from anyone!

**Comment by Wingless-Archangel** [comment]
Can you reopen this case?

I can't compile even you add the extra flags. it still struck at the first PATH for both LDFLAGS and CFLAGS

also I have a problem with `make static` that the architecture not supported.
