### ISSUE TITLE
HTTP response testing (--http option) depends on the local OpenSSL version

### ISSUE THREAD

**Issue by Sija** [rbsec/sslscan#220]
Ok, I see what the problem is. Basically , there are two different ways that sslscan checks if a cipher is allowed.

If the cipher is supported by our local openssl (or the version that sslscan was statically compiled against), then it will make a full connection using OpenSSL, and can then make the HTTP request.

However, if it's a cipher that isn't supported locally, then we sslscan manually creates a `ClientHello`, and then checks whether the server returns an error or a `ServerHello` - but it never actually completes the handshake (because it can't). This means that it won't be able to make the HTTP request.

I tried manually connecting with those ciphers from a client that did support them, and the server was returning a `200 OK` as expected. So the issue is on our side, not theirs.

---

I'm not really sure what we can do about this - sslscan will only ever be able to make a proper connection with the ciphers supported in the version of OpenSSL it's using, so we 're not going to be able to actually communicate with servers that use other ciphers. I think all we can really do is mark these ciphers as `N/A` or `Unsupported` or something in the output - although not sure how to make it clear that it's *us* that doesn't support them in the limited space.

To be honest, I'm slightly tempted just to remove the entire `--http` option - I've almost never seen it used, and I'm not sure that this issue can be solved in a nice way - but I'll have a think if there's any other options.

@jtesta do you have any thoughts on this?

_Originally posted by @rbsec in https://github.com/rbsec/sslscan/issues/219#issuecomment-706703778_

**Comment by jtesta** [comment]
> To be honest, I'm slightly tempted just to remove the entire --http option - I've almost never seen it used, and I'm not sure that this issue can be solved in a nice way - but I'll have a think if there's any other options.

I've never used `--http`, and I'm having trouble imagining why anyone else would, either.  One option is to remove it, then if a user complains, see if their use case makes sense and possibly re-add it.  (I'd be surprised if this happened.)

> I think all we can really do is mark these ciphers as N/A or Unsupported or something in the output - although not sure how to make it clear that it's us that doesn't support them in the limited space.

Another idea is we mark them `HTTP Untested`.  That would tell the user that we didn't run the HTTP test.  Perhaps the man page / usage output can further explain that this means the server supports the cipher, but we don't have the ability to make a full connection.

Personally, I'm leaning towards just removing `--http` entirely.

**Comment by rbsec** [comment]
@jtesta I think you're right - I've never really seen the point of that option, and it's now fairly broken - so I think just removing it is the best way forward.
