### ISSUE TITLE
Cannot use --targets and --xml together

### ISSUE THREAD

**Issue by michalmiddleton** [rbsec/sslscan#223]
Hi, 
It appears that I cannot use --targets and --xml together in one command. If I work with the same subset of servers separately, either --targets or --xml work ok. 

Content of my targets.lst:
```
www.google.com:443
```

**This fails:** 
```
./sslscan --targets=targets.lst --xml=scan.xml
Version: 2.0.4-static
OpenSSL 1.1.1i-dev  xx XXX xxxx
```
scan.xml contains:
```
<?xml version="1.0" encoding="UTF-8"?>
<document title="SSLScan Results" version="2.0.4-static" web="http://github.com/rbsec/sslscan">
  <error><![CDATA[Could not open targets file targets.lst.]]></error>
  <error><![CDATA[Targets file targets.lst does not exist.]]></error>
</document>
```

**This works OK:** `./sslscan --xml=scan.xml www.google.com:443`
**This also works OK:** `./sslscan --targets=targets.lst`

**Comment by rbsec** [comment]
Thanks for reporting this - it was a slightly interesting bug that took me a little while to work out.

The previous code was:

```c
if (condition)
    printf_error(...);
else
{
    // Do other stuff
}
```

The missing braces after the if are valid, *but only if there's a statement line before the else*. And while it's a single line, the changes to `printf_error()` in b72b28dcafa75e7e32ad1ac5a50b9457fee3356e mean that it's now a macro that expands to multiple lines - so the code isn't valid any more. A good example of why missing the braces is dangerous (even if it's valid).

**Comment by michalmiddleton** [comment]
Wow. That’s a good one! Thank you for fixing it right away!
