### ISSUE TITLE
Don't perform server signature algorithm checks by default

### ISSUE THREAD

**Issue by rbsec** [rbsec/sslscan#236]
I'm considering whether it's best to hide this by default, and have it as an option that users can select for a few reasons:

* I've had quite a lot of queries about it, and a lot of people not understanding it.
* It often suggests a problem when there isn't really one.
* In the vast majority of cases you can't really do anything about it (very few applications let you configure this).
* It's not really useful for the majority of people running the tool.

@jtesta do you have any thoughts on the above?

**Comment by anantshri** [comment]
I would second your thoughts. Make it available as a switch off by default. If someone wants, they can toggle. it creates confusion.

**Comment by jtesta** [comment]
Ok.  If most people don't find it useful, then switching it to disabled
by default seems like the right move.

**Comment by rbsec** [comment]
Cool - I've disabled in by default in version 2.0.7 and changed the option to `--show-sigs`

**Comment by Peneheals** [comment]
@rbsec A bit late in the game, but I would also like to mention that there is inconsistency between coloring:

Meanwhile bogus is red, https://github.com/rbsec/sslscan/blob/dd92203559e1a71afe46de3a2e88c828234786cc/sslscan.c#L5571

in the overall report bogus means (just) yellow: https://github.com/rbsec/sslscan/blob/dd92203559e1a71afe46de3a2e88c828234786cc/sslscan.c#L5721

I think the report should also use red.

**Comment by rbsec** [comment]
@Peneheals good spot - I've fixed that in a49aee1.
