### ISSUE TITLE
Certificate information cannot be retrieved

### ISSUE THREAD

**Issue by sgf-dma** [rbsec/sslscan#237]
Hi.

On some servers I sometimes start to encounter an error "Certificate information cannot be retrieved" with recent sslscan versions. Bisect found, that offending commit is 7abdd8f57afc5857b1b4f626f404ba49bc3d9579 . Reverting this commit (only modification to 'sslscan.c' near error message) fixes the issue.

Issue may be reproduced on this ancient (windows) server: 213.108.251.40 .

    $ ./sslscan --no-cipher-details --no-ciphersuites --no-compression --no-fallback --no-groups --no-heartbleed --no-renegotiation 213.108.251.40

    Version: 2.0.7-static
    OpenSSL 1.1.1k-dev  xx XXX xxxx

    Connected to 213.108.251.40

    Testing SSL server 213.108.251.40 on port 443 using SNI name 213.108.251.40

      SSL/TLS Protocols:
    SSLv2     disabled
    SSLv3     disabled
    TLSv1.0   enabled
    TLSv1.1   disabled
    TLSv1.2   disabled
    TLSv1.3   disabled

    Certificate information cannot be retrieved.

Though, if i disable everything except TLS 1.0 on relatively new nginx 1.14.2 (Debian 10) i can't reproduce the issue.

**Comment by rbsec** [comment]
Thanks for a very detailed error report, and also for providing a test case. The `TLS_client_method()` function *should* negotiate a protocol that's supported by both ends - but that relies on standards being followed, which clearly isn't the case here. If this is causing sslscan to miss certificates then I think that this change need to be reverted. Any objections @jtesta ?

**Comment by jtesta** [comment]
No objections here!


On Thu, 2021-02-18 at 04:52 -0800, rbsec wrote:
> Thanks for a very detailed error report, and also for providing a
> test case. The TLS_client_method() function should negotiate a
> protocol that's supported by both ends - but that relies on standards
> being followed, which clearly isn't the case here. If this is causing
> sslscan to miss certificates then I think that this change need to be
> reverted. Any objections @jtesta ?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
-- 
Joseph S. Testa II
Founder & Principal Security Consultant
Positron Security

**Comment by rbsec** [comment]
@sgf-dma I've (partially) reverted that commit, and it seems to work now on the test case you provided. Would you be able to double check that it's working ok for you?

**Comment by sgf-dma** [comment]
Thanks. Yes, it's working for me too.
