### ISSUE TITLE
Add self-signed certificate heading

### ISSUE THREAD

**Issue by mandreko** [rbsec/sslscan#24]
Since it looks like a large amount of the certificate data has been removed from this version, it'd be worthwhile to show if a certificate is self-signed, similar to how the TLS Renegotiation, TLS Compression, and Heartbleed detections work.

I would imagine something like:

```
➜  sslscan git:(master) ✗ ./sslscan 10.0.0.1
Version: 1.9.8-rbsec-wip-static
OpenSSL 1.0.1j 15 Oct 2014

Testing SSL server 10.0.0.1 on port 443

  TLS renegotiation:
Secure session renegotiation supported

  TLS Compression:
Compression disabled

  Heartbleed:
TLS 1.0 not vulnerable to heartbleed
TLS 1.1 not vulnerable to heartbleed
TLS 1.2 not vulnerable to heartbleed

  Certificate signature:
Self-signed

  Supported Server Cipher(s):
Accepted  SSLv3    256 bits  DHE-RSA-CAMELLIA256-SHA
Accepted  SSLv3    256 bits  AES256-SHA
Accepted  SSLv3    256 bits  CAMELLIA256-SHA
Accepted  SSLv3    128 bits  DHE-RSA-AES128-SHA
Accepted  SSLv3    128 bits  DHE-RSA-CAMELLIA128-SHA
Accepted  SSLv3    128 bits  AES128-SHA
Accepted  SSLv3    128 bits  CAMELLIA128-SHA
```

**Comment by rbsec** [comment]
Basic detection of self-signed/invalid certs implemented in previous few commits. I may add further checks if I keep running into the same type of cert issue.

**Comment by mandreko** [comment]
This may be dumb, but in addition to coloring it red, would it make sense to print "Potentially self-signed", for client report screenshots? The text being red may not be immediately identifiable as self-signed.
