### ISSUE TITLE
Request.

### ISSUE THREAD

**Issue by darkrenz** [rbsec/sslscan#240]
Is it possible to export the result into txt file? Im having an issue with bulk ip on Termux due to limited view all ip's that i already scan can't view anymore.

I might have to cut half of the IP RANGE to view it.

**Comment by rbsec** [comment]
There's no text output option directly in sslscan, but you can always redirect the output to a text file (you might want to pass `--no-colour` to get rid of the ANSI codes). Alternatively, if you're doing something automated with a lot of results, you might be better off with the XML output.

**Comment by darkrenz** [comment]
Sorry if i ask you this question, I literally no idea where to start, I'm not familiar with the coding.

What command i should use ex. I wanto to save TLS 1.3 Enabled only.

**Comment by rbsec** [comment]
There's no native functionality built into sslscan for this, but you could you pull out the info you want with grep. Something like

```sh
sslscan --no-heartbleed --no-compression --no-renegotiation --no-fallback --no-groups --no-ciphersuites --no-check-certificate --targets=targets.txt | grep -E "^Testing|^TLSv1.3"
```

**Comment by darkrenz** [comment]
Thanks for this info. It difinitely helps me ^^
