### ISSUE TITLE
TLS Result sometimes not accurate.

### ISSUE THREAD

**Issue by darkrenz** [rbsec/sslscan#242]
I've got a list of tls ip's that works well, unfortunately some of them can't read as "Enabled" even though it works very well. Heres the sample.

Through Injector
![Screenshot_2021-03-28-02-43-16-932_com evozi injector](https://user-images.githubusercontent.com/30442976/112730965-76128880-8f6f-11eb-9cc7-d684e7800afa.jpg)

Through Injector (If not working)
![Screenshot_2021-03-28-02-46-41-670_com evozi injector](https://user-images.githubusercontent.com/30442976/112731040-eb7e5900-8f6f-11eb-80ba-691c4262dffd.jpg)

Through Script (these ip's is working but some of them can't read as enabled)
![Screenshot_2021-03-28-02-42-56-873_com termux](https://user-images.githubusercontent.com/30442976/112730979-8b87b280-8f6f-11eb-81a3-5353d0801279.jpg)

I already tried turning on ssl2 or ssl3 if it has something to do with them, Hoping that i will have enabled response. Same as TLSversions It's disabled

Even though ip address working fine but if it doesn't certificate. It will look as disabled

**Comment by darkrenz** [comment]
You will see the ip's with enabled this is how it response in injector.
![Screenshot_2021-03-28-03-00-12-942_com evozi injector](https://user-images.githubusercontent.com/30442976/112731378-d0144d80-8f71-11eb-9262-4fc564547a7d.jpg)

**Comment by rbsec** [comment]
I don't really understand what issue you're having. Is there a specific IP address that you're getting inconsistent results for?

The screenshots look like they show the same results: .0 isn't accessible, and .1 has TLSv1.1 - TLSv1.3 enabled. Are you able to share a PCAP that shows the issue you're having?

**Comment by darkrenz** [comment]
104.17.64.0 - Does have TLS Supports no certificate. But it works.

![IMG_20210328_040428](https://user-images.githubusercontent.com/30442976/112733414-e541aa00-8f7a-11eb-817a-067a5dc99d08.jpg)

**Comment by darkrenz** [comment]
How do i capture pcap result?

**Comment by rbsec** [comment]
Are you sure that has a working TLS server? Because the [screenshot you posted](https://user-images.githubusercontent.com/30442976/112730965-76128880-8f6f-11eb-9cc7-d684e7800afa.jpg) shows the connection to it failing.

**Comment by darkrenz** [comment]
> Are you sure that has a working TLS server? Because the [screenshot you posted](https://user-images.githubusercontent.com/30442976/112730965-76128880-8f6f-11eb-9cc7-d684e7800afa.jpg) shows the connection to it failing.

Yes. We are currently using it to bypass internet, i mean w/o any subscription we are able to browse internet.

**Comment by darkrenz** [comment]
![IMG_20210328_041248](https://user-images.githubusercontent.com/30442976/112733603-e921fc00-8f7b-11eb-9efd-1b4d9448ec9b.jpg)
Here's the proof that it works.

**Comment by darkrenz** [comment]
Here's the proof. That it works.
![IMG_20210328_041512](https://user-images.githubusercontent.com/30442976/112733676-4ddd5680-8f7c-11eb-8139-4b4cb669aeae.jpg)

**Comment by rbsec** [comment]
Whatever is running on that IP, it doesn't successfully handshake with OpenSSL GnuTLS or Chrome - so it's either got some other restrictions on it's not a normal TLS stack. Either way, sslscan won't detect it because the underlying OpenSSL implementation won't connect to it.

**Comment by ImJeremy0** [comment]
Ssl scan installation for Android: 👇

termux-setup-stotage
pkg update && pkg upgrade
pkg install python
pkg install nmap
pkg install git
git clone github.com/dinotools/sslscan
pkg install sslscan
sslscan
Termux Command: 👇

Method#1: 👇

nmap -sL -n 104.16.96.0/24 | awk '/Nmap scan report for /{print $NF}' > Bughost1.txt

sslscan --no-check-certificate --no-ciphersuites --no-fallback --no-renegotiation --no-compression --no-heartbleed --no-check-certificate --no-sigs --no-heartbleed --no-groups --tlsall --timeout=1s --send-timeout=0s --targets=Bughost1.txt | awk '/Connected/ || /enabled/{print}' > Bughost1res.txt

cat result.txt

Could you please give me guide it is my favorite Bughost hunting tools, my issue is How to make it accurate again on my Cellphone?🙏🙏

all i know is When it has tls version enable, its automatically a bughost... Waiting to be fix This favorite tools of mine..🤗🤗

**Comment by darkrenz** [comment]
> Ssl scan installation for Android: 👇
> 
> termux-setup-stotage
> pkg update && pkg upgrade
> pkg install python
> pkg install nmap
> pkg install git
> git clone github.com/dinotools/sslscan
> pkg install sslscan
> sslscan
> Termux Command: 👇
> 
> Method#1: 👇
> 
> nmap -sL -n 104.16.96.0/24 | awk '/Nmap scan report for /{print $NF}' > Bughost1.txt
> 
> sslscan --no-check-certificate --no-ciphersuites --no-fallback --no-renegotiation --no-compression --no-heartbleed --no-check-certificate --no-sigs --no-heartbleed --no-groups --tlsall --timeout=1s --send-timeout=0s --targets=Bughost1.txt | awk '/Connected/ || /enabled/{print}' > Bughost1res.txt
> 
> cat result.txt
> 
> Good eve Mr. Author,
> Could you please give me guide♥️ it is my favorite Bughost hunting tools, my issue is How to make it accurate again on my Cellphone?🙏🙏
> 
> all i know is When it has tls version enable, its automatically a bughost... Waiting to be fix This favorite tools of mine..🤗🤗

It can be accurate like pc version hunting.

**Comment by darkrenz** [comment]
Pc version is much accurate than termux. I barely remember it but someone posted in on our forum but i cant use it since its pc version.

**Comment by rbsec** [comment]
@darkrenz and @ ImJeremy0 - you're cloning a completely different fork of sslscan.

The Git repo in your commands is `github.com/dinotools/sslscan`, which is not this project - so you'll have more luck getting support by creating an issue there.
