### ISSUE TITLE
Windows precompiled binaries

### ISSUE THREAD

**Issue by beppler** [rbsec/sslscan#244]
Hi.

First, thanks for this awesome project.

I'm using it on Windows and on README there is an indication that WIndows binaries should be found on Releases pages, but the last one available is for version 2.0.0.

Can you generate the binaries for newer releases?

**Comment by rbsec** [comment]
Hi @beppler 

There should have been a Windows binary attached to the 2.0.9 release. Looking at the tag, the file apparently hadn't uploaded properly, so it was listed in the properties but wasn't actually available. There was one for the 2.0.7 tag though.

I've just pushed 2.0.10 which should have a Windows binary - so you can use that.

Thanks.
