### ISSUE TITLE
debian compile instructions

### ISSUE THREAD

**Issue by anantshri** [rbsec/sslscan#25]
Debian doesn't have `build-essentials` rather it has `build-essential` notice non existing s in the end.

https://packages.debian.org/search?keywords=build-essential&searchon=names&suite=stable&section=all

https://packages.debian.org/search?keywords=build-essentials&searchon=names&suite=stable&section=all

A note for this would help.

**Comment by rbsec** [comment]
Thanks - fixed the typo.
