### ISSUE TITLE
TLS version not Accurate, How to fix This?

### ISSUE THREAD

**Issue by ImJeremy0** [rbsec/sslscan#252]
Closed,

**Comment by ImJeremy0** [comment]
![IMG_20210909_075233](https://user-images.githubusercontent.com/89556550/132600482-832e1b71-4947-4c54-b1cc-48cc106007d4.jpg)

It has tls version support before.
45.60.150.66
45.60.154.66
45.60.158.66
45.60.162.66
45.60.166.66
45.60.170.66

I used the repository of yours before, not by dinotools because you have the latest version... And your tools is my favorite of all the tools.. Could you help me?

**Comment by ImJeremy0** [comment]
This is the Version of tools thats my favorite, 
👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇



Sorry for the pic.. The date i scan thi is April 28 2021

**Comment by jtesta** [comment]
Using the master branch of sslscan against the first IP you listed, it does find the TLS versions enabled:
```
$ ./sslscan 45.60.150.66:443
Version: 2.0.10-4-g5224502-static
OpenSSL 1.1.1m-dev  xx XXX xxxx

Connected to 45.60.150.66

Testing SSL server 45.60.150.66 on port 443 using SNI name 45.60.150.66

  SSL/TLS Protocols:
SSLv2     disabled
SSLv3     disabled
TLSv1.0   disabled
TLSv1.1   disabled
TLSv1.2   enabled
TLSv1.3   enabled

[...]
  Supported Server Cipher(s):
Preferred TLSv1.3  128 bits  TLS_AES_128_GCM_SHA256        Curve 25519 DHE 253
Accepted  TLSv1.3  256 bits  TLS_CHACHA20_POLY1305_SHA256  Curve 25519 DHE 253
Accepted  TLSv1.3  256 bits  TLS_AES_256_GCM_SHA384        Curve 25519 DHE 253
[...]
```
It returns similar results for the the other IPs you listed as well.

Are you sure that your commands are using the right version of sslscan?  What happens when you run `sslscan --version` ?

**Comment by ImJeremy0** [comment]
![Uploading Screenshot_2021-09-09-08-07-49-56.png…]()

**Comment by ImJeremy0** [comment]
> Using the master branch of sslscan against the first IP you listed, it does find the TLS versions enabled:
> 
> ```
> $ ./sslscan 45.60.150.66:443
> Version: 2.0.10-4-g5224502-static
> OpenSSL 1.1.1m-dev  xx XXX xxxx
> 
> Connected to 45.60.150.66
> 
> Testing SSL server 45.60.150.66 on port 443 using SNI name 45.60.150.66
> 
>   SSL/TLS Protocols:
> SSLv2     disabled
> SSLv3     disabled
> TLSv1.0   disabled
> TLSv1.1   disabled
> TLSv1.2   enabled
> TLSv1.3   enabled
> 
> [...]
>   Supported Server Cipher(s):
> Preferred TLSv1.3  128 bits  TLS_AES_128_GCM_SHA256        Curve 25519 DHE 253
> Accepted  TLSv1.3  256 bits  TLS_CHACHA20_POLY1305_SHA256  Curve 25519 DHE 253
> Accepted  TLSv1.3  256 bits  TLS_AES_256_GCM_SHA384        Curve 25519 DHE 253
> [...]
> ```
> 
> It returns similar results for the the other IPs you listed as well.
> 
> Are you sure that your commands are using the right version of sslscan? What happens when you run `sslscan --version` ?

It doesn't give tls version.. I dont know how to fix, Thanks for the comments bro😊😊

**Comment by jtesta** [comment]
Try running `sslscan --version` on your Android device and copy/pasting the output here.

**Comment by ImJeremy0** [comment]
![Uploading Screenshot_2021-09-09-08-12-32-05.png…]()

**Comment by ImJeremy0** [comment]
Done.

**Comment by jtesta** [comment]
Interesting.  You do seem to be using the latest version of sslscan, but running it on Android results in no protocols being detected.  When I run sslscan against the same IP on my desktop machine, I find TLSv1.2 and v1.3 enabled!

I suppose we'd have to debug this further on an Android system.  What exact version of Android are you using?  A stock version from Google, or a custom build?

**Comment by ImJeremy0** [comment]
Closed,
