### ISSUE TITLE
Windows Server 2022 TLSv1.3

### ISSUE THREAD

**Issue by RvdHout** [rbsec/sslscan#253]
Running the tool multiple times can give unexpected results, 
one time it says TLSv1.3 is enabled, another time it says it is not

**Comment by jtesta** [comment]
Would you happen to know an externally-available host that exhibits
this behavior?  If so, we can begin to debug this issue.

-- 
Joseph S. Testa II
Founder & Principal Security Consultant
Positron Security

**Comment by RvdHout** [comment]
Unfortunately not (yet), i running it in a Hyper-V VM instance right now to test compatibility with web-applications, migration
