### ISSUE TITLE
About the latest release

### ISSUE THREAD

**Issue by chenrui333** [rbsec/sslscan#257]
👋  it looks like `2.0.11` was not marked as the `latest release`, can you confirm if it is intended? Thanks!

- relates to https://github.com/Homebrew/homebrew-core/pull/91606

**Comment by rbsec** [comment]
Oops, I'd forgotten that I needed to make a release as well as tagging. Maybe one day I'll setup CI/CD to do that automatically....

New release is here: https://github.com/rbsec/sslscan/releases/tag/2.0.11

Thanks.

**Comment by chenrui333** [comment]
@rbsec, np, thanks for marking the latest release! :)

**Comment by rbsec** [comment]
@chenrui333 I should really sort out some automation for this so stop me forgetting. I've marked 2.0.12 as a release, but I don't have access to my Windows build environment ATM, so I'll have to sort out the Windows binary at some point.

For future reference, the latest tag in the 2.x.x series is always considered the latest version. If it's not marked as release on GitHub that's just me forgetting to mark it - it's not anything to do with whether it's considered ready or not.

**Comment by chenrui333** [comment]
I can actually help you automate this a bit.
