### ISSUE TITLE
Missing information from XML when certificate not yet valid

### ISSUE THREAD

**Issue by lucacapacci** [rbsec/sslscan#259]
In sslscan.c, in the "if (options->xmlOutput)" block code related to the not-valid-before (lines 2322-2326) there is no XML reporting about certificate not valid. I would have expected something like the "if (options->xmlOutput)" block code related to  the not-valid-after, which in lines 2345-2352 writes in the XML the outcome of the time diff.

**Comment by jtesta** [comment]
Are you saying that you'd like the non-XML output say something like "Certificate validity: expired" ?

FYI, expired certificates are already shown to the user in red.  See: https://github.com/rbsec/sslscan/blob/3fa40d0a43032c6f0d98248611d515094c63fc15/sslscan.c#L2333

**Comment by lucacapacci** [comment]
Hi Joe, nope, I'm afraid I didn't explain the right way. I'm saying that I'd like the XML output say something like "<not-yet-valid>true</not-yet-valid>".

To be more precise, right now the lines 2322-2326 are these:
```
if (options->xmlOutput) {
      printf_xml("   <not-valid-before>");
      ASN1_TIME_print(fileBIO, X509_get_notBefore(x509Cert));
      printf_xml("</not-valid-before>\n");
}
```
I'd like them to be something like this:
```
if (options->xmlOutput) {
      printf_xml("   <not-valid-before>");
      ASN1_TIME_print(fileBIO, X509_get_notBefore(x509Cert));
      printf_xml("</not-valid-before>\n");
      if (timediff > 0)
      {
          printf_xml("   <not-yet-valid>true</not-yet-valid>\n");
      }
      else
      {
          printf_xml("   <not-yet-valid>false</not-yet-valid>\n");
      }
}
```

**Comment by lucacapacci** [comment]
I think in many years it happened to me just one time and I don't remember the host in which it happened. However, I'm developing an XML parser for sslscan and I thought it would be nice to take into account even these edge cases.

**Comment by rbsec** [comment]
Fair enough. I was wondering if there was some vendor out there who was doing this, but if it's just for completeness that makes sense.
