### ISSUE TITLE
[Question] Cipher strength levels

### ISSUE THREAD

**Issue by joaociocca** [rbsec/sslscan#279]
I have just a quick question about strength levels.
Is medium better or worse than acceptable?

**Comment by rbsec** [comment]
"Acceptable" is the default strength listed in the XML output when none of the other conditions (low bits, known bad modes, etc) are matched - it's basically the equivalent to the white output fro the CLI.

The ciphers are better than the ones flagged as "medium" (which is things like RC4), but worse than the ones flagged as "strong".

**Comment by joaociocca** [comment]
So, for putting in a plain scale:

Medium - acceptable - strong

Did I understand correctly?

Em dom., 26 de mar. de 2023 07:42, rbsec ***@***.***>
escreveu:

**Comment by rbsec** [comment]
That's correct. Or more completely:

Null < Weak < Medium < Acceptable < Strong

**Comment by joaociocca** [comment]
awesome. Thank you very much for that!
