### ISSUE TITLE
Feature Request : Write "security colors" as a text in XML output

### ISSUE THREAD

**Issue by vinch1266** [rbsec/sslscan#286]
Hi,

Thanks for the wonderful job !
It would be amazing if we could have the security advisories (corresponding to the Red/Yellow/Green colors in the output) as a text in the XML file, so we could easily identify if something could be improved in the server's configuration.

Regards

**Comment by rbsec** [comment]
Hi @vinch1266 ,

There isn't a full mapping of all of the colours output (things like the certificates and supported protocols aren't shown - although the information in there to let you decide whether you're happy with them). However, the colours for the ciphers  are mapped to the `strength` attribute in the XML:

* Red = `weak`
* Yellow = `medium`
* White = `acceptable`
* Green = `strong`

So perhaps that provides the information you're looking for?
