### ISSUE TITLE
Multiple improvements for the Makefile

### ISSUE THREAD

**Issue by rhertzog** [rbsec/sslscan#29]
In http://git.kali.org/gitweb/?p=packages/sslscan.git;a=tree;f=debian/patches;h=0e998c170e55127ca5878f6d380b5daa8ad89127;hb=HEAD you will find 3 patches that we need to create a proper Kali package:

* Fix-clean-test.patch: this ensures that "make clean" doesn't fail when there's no openssl directory
* Fix-flags.patch: this preserves the user-supplied CFLAGS/LDFLAGS so that hardening build flags can be injected by the packaging tools. In fact you should also include ${CPPFLAGS} in your sslscan compilation command-line...
* Fix-install-path.patch: this makes it possible for us to do "make install DESTDIR=debian/sslscan" and get the files installed in the package build directory (this variable is standardized in autoconf/automake generated makefiles).

It would be nice if you could include those improvements.

**Comment by rbsec** [comment]
Great to see this has been picked up by Kali (and will save me having to build it from source on my own Kali installs).

I've merged those three patches - let me know if there are any other changes that will make your life easier.

**Comment by rbsec** [comment]
Patches included in the latest tagged release (1.9.11). I've also fixed the version number not showing up when statically building from a tarball (was just showing "-static" as the version in Kali).
