### ISSUE TITLE
TLS 1.3 Inconsistent results

### ISSUE THREAD

**Issue by dimante** [rbsec/sslscan#296]
TLS 1.3 not enabled on server.   SSLSCAN run the 1st / 2nd time reflects this.  Run a 3rd or sometimes even on the second shows it is enabled and returns two cipher suites..  Why the inconsistencies between runs?

**Comment by jtesta** [comment]
If we have a target host to test against, then we can take a closer
look and debug the issue.  If you'd like to provide it in private, my
e-mail address is: jtesta at-sign positronsecurity dot com.

**Comment by dimante** [comment]
Emailed it to you.  Although anything I test produces the same inconsistency.

**Comment by dimante** [comment]
Recompiled latest github pull and this one seems to be ok.  If you test the same, I think we can close this.  I even set the registry enabled 0 for tls 1.3 temporarily to test and it came back disabled every time.

**Comment by dimante** [comment]
So, for instance.  This version is not showing my Poly cipher as preferred, I confirmed that it is (Validated against SSLLabs).  Are you seeing the same?

**Comment by jtesta** [comment]
The master branch of sslscan produces the following against your target
host:

  Supported Server Cipher(s):
Preferred TLSv1.3  256 bits  TLS_CHACHA20_POLY1305_SHA256  Curve 25519
DHE 253
Accepted  TLSv1.3  128 bits  TLS_AES_128_GCM_SHA256        Curve 25519
DHE 253
Accepted  TLSv1.3  256 bits  TLS_AES_256_GCM_SHA384        Curve 25519
DHE 253
Preferred TLSv1.2  256 bits  ECDHE-RSA-AES256-GCM-SHA384   Curve P-384
DHE 384
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-GCM-SHA256   Curve 25519
DHE 253

This is the same result that SSLLabs is returning for both TLSv1.2 and
v1.3.

**Comment by dimante** [comment]
Once it gets a result is there a cache?  Does something have to be cleared
as I do not see that order reflected when I do the same...

Best regards,

John Gates, CISSP, CDPSE, CEH, CHFI

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

**Comment by dimante** [comment]
I see what was happening.  Thank you for checking this.  Have a good day!

**Comment by jtesta** [comment]
No problem!
