### ISSUE TITLE
Error when COPY --from=builder /lib/ld-musl-x86_64.so.1 /lib/ld-musl-x86_64.so.1:

### ISSUE THREAD

**Issue by derekmizak** [rbsec/sslscan#300]
There is an error when building docker:
```
=> ERROR [stage-1 3/3] COPY --from=builder /lib/ld-musl-x86_64.so.1 /lib  0.0s
------
 > [stage-1 3/3] COPY --from=builder /lib/ld-musl-x86_64.so.1 /lib/ld-musl-x86_64.so.1:
------
Dockerfile:26
--------------------
  24 |     COPY --from=builder /builddir/sslscan /sslscan
  25 |     COPY --from=builder /lib/libz.so.1 /lib/libz.so.1
  26 | >>> COPY --from=builder /lib/ld-musl-x86_64.so.1 /lib/ld-musl-x86_64.so.1
  27 |     
  28 |     # Drop root privileges.
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 1cf22f97-0c34-4b17-bb12-042ed41fd824::3mrwz7mv4ex0rmgenxj0gcrda: "/lib/ld-musl-x86_64.so.1": not found
make: *** [docker] Error 1
```

**Comment by jtesta** [comment]
I can't seem to reproduce this error:

```
 ---> c215d77c7ff4
Step 10/15 : FROM scratch
 ---> 
Step 11/15 : COPY --from=builder /builddir/sslscan /sslscan
 ---> 49d45d65664c
Step 12/15 : COPY --from=builder /lib/libz.so.1 /lib/libz.so.1
 ---> e0c99f39eba2
Step 13/15 : COPY --from=builder /lib/ld-musl-x86_64.so.1 /lib/ld-musl-
x86_64.so.1
 ---> 6b63a33358a0
Step 14/15 : USER 65535:65535
 ---> Running in 1843bec11fce
Removing intermediate container 1843bec11fce
 ---> 7b696eb989b1
Step 15/15 : ENTRYPOINT ["/sslscan"]
 ---> Running in fb3ef2ddfd7f
Removing intermediate container fb3ef2ddfd7f
 ---> cded6018ffc1
Successfully built cded6018ffc1
```

This is using the `master` branch of sslscan, along with Docker
v24.0.5.  What code branch and Docker version are you using?

**Comment by rbsec** [comment]
Does `ld-musl-x86_64.so.1` exist in the `alpine:latest` Docker image for you? The build works fine on for me on x64 Kali Linux - so I presume this is an OSX/M1 related problem?

**Comment by jtesta** [comment]
It just occurred to me: alpine:latest is likely the ARM build on
MacOSX/M1, whereas its x86_64 on our machines.  Hence, there is no ld-
musl-x86_64.so.1 on ARM; its probably called ld-musl-arm.so.1 or
something.

@derekmizak: on line 26 of the Dockerfile, could you change it to read
"COPY --from=builder /lib/ld-musl-*.so.1 /lib/" and try again?

**Comment by rbsec** [comment]
@derekmizak that should be merged into master now.

@jtesta, I suspected that it would be something like that when I saw the error - but TBH I've never really looked at the ARM docker images.

**Comment by derekmizak** [comment]
It is fixed - thank you.
