### ISSUE TITLE
Windows 2.1.2 release zip file contains 2.1.1 pre-compiled binary

### ISSUE THREAD

**Issue by arcao** [rbsec/sslscan#302]
`sslscan --version` shows:

```
                2.1.1 Windows 64-bit (Mingw)
                OpenSSL 3.0.9 30 May 2023
```

**Comment by sergeevabc** [comment]
Err… @rbsec, @@jtesta, hello?

**Comment by jtesta** [comment]
This would be a task for rbsec to update the release since he's the
official maintainer.  I just send in patches from time to time.

**Comment by rbsec** [comment]
There's a new 2.1.3 release that should fix this.

**Comment by sergeevabc** [comment]
@rbsec, the package includes `sslscan.sig` file with no instructions in readme.md on how to use it.

**Comment by rbsec** [comment]
It's a GPG signature - you can verify it against previous releases, and my key is on public keyservers.

**Comment by sergeevabc** [comment]
@rbsec
* [keys.openpgp.org](https://keys.openpgp.org/search?q=rbsec)/search?q=rbsec)
Invalid search query
* [keyserver.pgp.com](https://keyserver.pgp.com/vkd/SubmitSearch.event?SearchCriteria=rbsec)
No results were found
* [keyserver.ubuntu.com](https://keyserver.ubuntu.com/pks/lookup?search=rbsec&fingerprint=on&op=index)
Found! But wait…

![2024-0121-2217 rbsec expired pgp key](https://github.com/rbsec/sslscan/assets/373718/c10a7d3d-e431-42ef-9a9a-13c3cc5eccf7)

**Comment by rbsec** [comment]
My GPG key is available on the Ubuntu keyserver (https://keyserver.ubuntu.com/pks/lookup?search=robin%40rbsec.net&fingerprint=on&op=index) and the OpenPGP keyserver (https://keys.openpgp.org/search?q=robin%40rbsec.net) under my email address.

**Comment by sergeevabc** [comment]
@rbsec, the trouble is that your e-mail address is not mentioned in `sslscan.exe --help` or in `readme.md`, and your Github profile has only @ sign on avatar. Seriously, try to put yourself in the ordinary user's shoes.

![2024-0121-2314 rbsec github profile](https://github.com/rbsec/sslscan/assets/373718/5c798f54-445a-47f1-bfcd-db4b9d23e2a7)

**Comment by rbsec** [comment]
Well if they've already run `sslscan --help` then it's far too late to be worrying about checking signatures, because they've already run the untrusted code.

And it's already listed in the changelog, the man page and the git commit history. But I can add it to the readme as well for people who don't bother looking at any of those.
