### ISSUE TITLE
XML output error for certificate with SCT

### ISSUE THREAD

**Issue by marcvdm** [rbsec/sslscan#36]
I just tried the following command
```sslscan --bugs --verbose --failed --show-client-cas --show-certificate www.networking4all.com```

One X509v3 extension that it may contain is the "1.3.6.1.4.1.11129.2.4.2".
This extension contains a certificate with embeded SCT (signed certificate timestamp) 

https://github.com/google/certificate-transparency/blob/master/test/testdata/README

The output for this specific ssl certificate on the command line is
```
......u.......X......gp
.....K_..|.....F0D. lc.O.s.......}=S(..:...Hj..(..... .r....g.M...0.eRZ4.sQ[......|E.@.w.V.../.......D.>.Fv....\....U.......K_..3.....H0F.!.....Z[.qn. .A....fcl).1..d...n.Y.!....i......*...K.).{...z*!4K..z..
```

On the xml output is different
```
......u.......X......gp
<5.......w...
.....K_..|.....F0D. lc.O.s.......}=S(..:...Hj..(.....
.r....g.M...0.eRZ4.sQ[......|E.@.w.V.../.......D.>.Fv....\....U.......K_..3.....H0F.!.....Z[.qn.
.A....fcl).1..d...n.Y.!....i......*...K.).{...z*!4K..z..
```

As you can see it contains a "<" on the second line which breaks the xml output.

I suggest that maybe the output is escaped for xml output or maybe another solution

**Comment by rbsec** [comment]
Thanks for the bug report.

Trying to do anything clever with the XML in C seems like a bad idea, so I've just wrapped the extensions in CDATA blocks to preserve the contents.

It's not an ideal solution, and looking at the output, a certain amount of data seems to be lost already (you get a file with lots of fullstops, when really I think they should be non-printable  chars). Something to look into...
