### ISSUE TITLE
Unable to run on Windows 8.1

### ISSUE THREAD

**Issue by AshleyPoole** [rbsec/sslscan#39]
When trying to run sslscan.exe from the command line I receive the below message which seems to point towards the exe isn't compatible with Windows 8.1.

This version of C:\Users\Ashley\Downloads\sslscan-win-1.10.0-rbsec\sslscan.exe is not compatible with the version of Windows that you're running. Check your computer's system information and then contact the software publisher.

**Comment by rbsec** [comment]
The Windows build should be considered experimental, I've tested it on Windows 7, but haven't ever tried to run it on another version. A few things you can try:

* Does it work if you set the compatibility mode to Windows 7?
* Are you running a 32 or 64 bit version of Windows? The binary is 64 bit.
* Have you tried compiling it natively in Windows 8.1 to see if that works?

~rbsec

**Comment by ph1ll** [comment]
I have just tested version 1.10.0-rbsec using the binary from the releases page on Windows 8.1 Pro x64 and can confirm it works as expected.
