### ISSUE TITLE
Too many connections on STARTTLS

### ISSUE THREAD

**Issue by Mitta** [rbsec/sslscan#50]
Windows 8.1 Enterprise.
Used: https://github.com/rbsec/sslscan/releases/download/1.10.0-rbsec/sslscan-win-1.10.0-rbsec.zip

I've got some issues with the --starttls-ftp function. When I try to test it on a server with vsftpd, it gives me this output:
![capture](https://cloud.githubusercontent.com/assets/3225912/8454457/c4f59a38-1ffd-11e5-89c8-c0c0c38ad130.PNG)

Any Ideas?

EDIT:

Added environment info

**Comment by rbsec** [comment]
The server is blocking you because you're making too many connections - there's not a huge amount you can do to prevent this. You could try using the --sleep option to pause between requests, which might work. Really depends what criteria the server is using to block you.

**Comment by Mitta** [comment]
Thanks for your reaction. I tried the --sleep option, but it didn't do much other than slowing it down. Isn't there something to fix this? I actually dont have these kind of problems with other tools like SSLyze.

**Comment by rbsec** [comment]
Since #62 sslscan now makes a lot less connections than before (depending slightly on the number of ciphers the sever supports). Combined with --sleep that should work on most servers, and beyond that there's not really much more that can be done.
