### ISSUE TITLE
Certificate Signature Algorithm False Positive

### ISSUE THREAD

**Issue by felixrr** [rbsec/sslscan#64]
Hi there,

I have noticed on a number of tests that the signature algorithm is being reportedly incorrectly.  Seems to happen when there is more than one signature on a cert, for example a SHA1 and a SHA256.  When this is the case, it only reports the first signature algorithm on the cert and as a result it looks like the cert is weaker than it really is.

Please can the output include all signature algorithms?

Thanks!

**Comment by rbsec** [comment]
I don't think I've ever seen an SSL cert with multiple signature algorithms (from the RFC I'm not sure if it's even possible?). I've seen servers sending multiple certificates - is that perhaps what's happening?

Could you provide an example certificate/site? If you'd rather not do so publicly then you can drop me an email on robin [0x40] rbsec.net

**Comment by felixrr** [comment]
Heya,

If you run the your tool over my blog site (not very exciting and can be found at felixrr.pro).  You will see a "correct" response.  If you then look at the cert, you will see that it has two signatures, one is SHA1 and one is SHA256.  I will see if I can find a site that has the false positive like I was describing to send you, unfortunately I can't send you the ones I have found so far as they are clients...

Thanks!

**Comment by rbsec** [comment]
I only see a SHA256 signature on the certificate on that site. Is it possible that you're confusing the signature algorithm with the [thumbprint algorithm](http://security.stackexchange.com/questions/71199/what-is-the-difference-between-a-thumbprint-algorithm-signature-algorithm-an), which is listed as sha1? As discussed on the Stackexchange link, the thumbprint is calculated client-side, it's not part of the certificate itself.

**Comment by felixrr** [comment]
You know what, you might be right.  Let me get back to you!

On 23/09/15 14:39, rbsec wrote:
>
> I only see a SHA256 signature on the certificate on that site. Is it
> possible that you're confusing the signature algorithm with the
> thumbprint algorithm
> <http://security.stackexchange.com/questions/71199/what-is-the-difference-between-a-thumbprint-algorithm-signature-algorithm-an>,
> which is listed as sha1? As discussed on the Stackexchange link, the
> thumbprint is calculated client-side, it's not part of the certificate
> itself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rbsec/sslscan/issues/64#issuecomment-142604152>.
>

-- 
To verify my identity please visit:

https://keybase.io/felixrr

**Comment by felixrr** [comment]
Yep.  I've been looking at the wrong value.  Cheers for the pointer! :D
