### ISSUE TITLE
Problems to compile new version on OS X

### ISSUE THREAD

**Issue by Vietwoojagig** [rbsec/sslscan#82]
Hi,
the new version does not compile on OS X anymore.

This is the output:

$ git clone https://github.com/rbsec/sslscan.git
Cloning into 'sslscan'...
remote: Counting objects: 1141, done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 1141 (delta 18), reused 0 (delta 0), pack-reused 1106
Receiving objects: 100% (1141/1141), 488.18 KiB | 0 bytes/s, done.
Resolving deltas: 100% (717/717), done.
Checking connectivity... done.

$ cd sslscan
$ make static
if [ -d openssl -a -d openssl/.git ]; then \
		cd ./openssl && git checkout OpenSSL_1_0_2-stable && git pull | grep -q "Already up-to-date." && [ -e ../.openssl.is.fresh ] || touch ../.openssl.is.fresh ; \
	else \
		git clone https://github.com/openssl/openssl ./openssl && cd ./openssl && git checkout OpenSSL_1_0_2-stable && touch ../.openssl.is.fresh ; \
	fi
Cloning into './openssl'...
remote: Counting objects: 189721, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 189721 (delta 1), reused 0 (delta 0), pack-reused 189716
Receiving objects: 100% (189721/189721), 81.46 MiB | 11.14 MiB/s, done.
Resolving deltas: 100% (150246/150246), done.
Checking connectivity... done.
Branch OpenSSL_1_0_2-stable set up to track remote branch OpenSSL_1_0_2-stable from origin.
Switched to a new branch 'OpenSSL_1_0_2-stable'
sed -i 's/# if 0/# if 1/g' openssl/ssl/s2_lib.c
sed: 1: "openssl/ssl/s2_lib.c": invalid command code o
make: *** [opensslpull] Error 1

**Comment by videoman** [comment]
On mac os x, edit the Makefile-, the sed command should be be "sed -i '' 's/# if 0/# if 1/g' openssl/ssl/s2_lib.c" 

Adding the -i '' to the command tells sed to do inplace edits.

**Comment by Vietwoojagig** [comment]
Would it be possible to add a condition to the Makefile that goes with
sed -i '' 's/# if 0/# if 1/g' openssl/ssl/s2_lib.c
in case of OS=Darwin and
sed -i 's/# if 0/# if 1/g' openssl/ssl/s2_lib.c 
in the other cases?

**Comment by apjanke** [comment]
You could use `-i.bak` unconditionally; that's compatible with both GNU and BSD `sed`s. (OS X provides BSD `sed`).

```
sed -i.bak 's/# if 0/# if 1/g' openssl/ssl/s2_lib.c
```
