### ISSUE TITLE
./Configure darwin64-x86_64-cc no-shares enable-weak-ssl-ciphers enable-ssl2 zlib

### ISSUE THREAD

**Issue by Vietwoojagig** [rbsec/sslscan#87]
Please adjust the make file in line 83 for OS X compilation:

`	cd ./openssl; ./Configure darwin64-x86_64-cc`

-->

`	cd ./openssl; ./Configure darwin64-x86_64-cc no-shares enable-weak-ssl-ciphers enable-ssl2 zlib`

**Comment by tessus** [comment]
the order is actually supposed to be the other way around:

`cd ./openssl; ./Configure enable-ssl2 enable-weak-ssl-ciphers zlib darwin64-x86_64-cc`

created a pull request #88 for it.

**Comment by rbsec** [comment]
For some reason this didn't get closed when the PR was merged (although from commit messages it should have).
